### PR TITLE
Updating Data Identification table

### PR DESCRIPTION
**Pull request by gizmocuz**

### CODE REVIEW

**Comment by dheitmueller** [comment]
So DID/SDID 0x41/0x0D isn't in the SMPTE-RA registry:

https://smpte-ra.org/smpte-ancillary-data-smpte-st-291

I have little reason to think this patch is incorrect, but I would probably want to put eyes on ST2108-2 to confirm before this is merged.

**Comment by dheitmueller** [comment]
@gizmocuz Sorry, I forgot to say, Thank you for your patch.  By all means we welcome patches of this nature to make libklvanc better!

**Comment by dheitmueller** [comment]
I've reviewed ST2108-2 and confirmed that indeed the DID/SDID are those referenced in the spec (See ST2108-2:2019 Sec 5.1).

This patch should be merged.

**Comment by stoth68000** [comment]
Many thanks!

**Pull request merged**
